{
 "title": "Modem Stats",
 "tags": [
  "modem",
  "virgin media",
  "isp",
  "hub5"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service name regex", "query": "${VAR_SERVICE}" }
  ]
 },
 "panels": [
  {
   "title": "Data Rates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemstats_config_maxrate{service=~\"$service\",config=\"downstream\"}",
     "legendFormat": "{{config}}"
    },
    {
     "expr": "modemstats_config_maxrate{service=~\"$service\",config=\"upstream\"}",
     "legendFormat": "{{config}}"
    }
   ]
  },
  {
   "title": "Statistics Fetch Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "modemstats_shstatsinfo_timems{service=~\"$service\"}",
     "legendFormat": "Scrape time"
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "modemstats_downstream_power{service=~\"$service\"}/10",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "targets": [
    {
     "expr": "modemstats_upstream_power{service=~\"$service\"}/10",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "modemstats_downstream_snr{service=~\"$service\"}/10",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "New Pre RS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(modemstats_downstream_prerserr{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "New Post RS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(modemstats_downstream_postrserr{service=~\"$service\"}[$__rate_interval])",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  }
 ]
}